version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_fasttask
    restart: always
    environment:
      MYSQL_DATABASE: fast_task_db
      MYSQL_USER: fast_task_user
      MYSQL_PASSWORD: fast_task_password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fasttask_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run build && npm run preview"
    ports:
      - "5173:4173"
    depends_on:
      - backend

volumes:
  db_data:
